spring.application.name=backend

# ENV
env=dev

# SERVER
server.port=${PORT:8080}

# Database config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/huly}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:4672}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

