

#SERVER
server.port=8080

#CORS
frontend.url=http://localhost:3000

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/huly
spring.datasource.username=postgres
spring.datasource.password=4672