spring.application.name=backend



# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/huly
spring.datasource.username=postgres
spring.datasource.password=4672
spring.datasource.driver-class-name=org.postgresql.Driver