

#SERVER
server.port=${PORT}

#CORS
frontend.url=${FRONTEND_URL}

#DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${S  PRING_DATASOURCE_PASSWORD}

#SWAGGER - explicitamente deshabilitado en produccion
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false