spring.application.name=backend

# ENV
env=dev

# SERVER
server.port=8900

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/huly
spring.datasource.username=postgres
spring.datasource.password=4672
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

